ASPNETCORE_2021_02/RazorPagesBasics/Pages/Modul002/PartialViewSample1.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesBasics.Pages.Modul002
{
    public class PartialViewSample1Model : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ASPNETCORE_2021_02/RazorPagesBasics/Pages/Modul002/PartialViewSample2.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesBasics.Pages.Modul002
{
    public class PartialViewSample2Model : PageModel
    {
        public string[] Tage { get; set; } = new string[7];

        public void OnGet()
        {

        }

        public PartialViewResult OnGetExcel()
        {
            for (int i = 0; i < 7; i++)
            {
                Tage[i] = Enum.GetName(typeof(DayOfWeek), i);
            }

            return Partial("_Excel", this);
        }
    }
}

ASPNETCORE_2021_02/RazorPagesBasics/Pages/Modul002/PartialViewSample3.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesBasics.Pages.Modul002
{
    public class PartialViewSample3Model : PageModel
    {

        public string[] Tage { get; set; } = new string[7];

        public void OnGet()
        {
        }

        public PartialViewResult OnGetExcel()
        {
            for (int i = 0; i < 7; i++)
            {
                Tage[i] = Enum.GetName(typeof(DayOfWeek), i);
            }

            return Partial("_Excel", this);
        }
    }
}

ASPNETCORE_2021_02/RazorPagesBasics/Pages/Modul002/PartialViewSample1.cshtml
@page
@model RazorPagesBasics.Pages.Modul002.PartialViewSample1Model
@{
}

<h1>Partial Beispiel 1 (Hauptseite)</h1>

<partial name="_Zeit" />

ASPNETCORE_2021_02/RazorPagesBasics/Pages/Modul002/PartialViewSample2.cshtml
@page
@model RazorPagesBasics.Pages.Modul002.PartialViewSample2Model
@{
}

<h1>PartialViewSample2</h1>

<a asp-page-handler="excel" class="btn btn-danger">Excel Export</a>

ASPNETCORE_2021_02/RazorPagesBasics/Pages/Modul002/PartialViewSample3.cshtml
@page
@model RazorPagesBasics.Pages.Modul002.PartialViewSample3Model
@{
}

<h1>jQuery Sample with PartialViews</h1>

<p><button class="btn btn-primary" id="btnLoadDayList">Load</button></p>


<div id="grid"></div>



@section scripts{
    <script>
        $(function () {
            $('#btnLoadDayList').on('click', function () {
                $('#grid').load('/Modul002/PartialViewSample3?handler=Excel');
            });
        });
    </script>
}